version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: .env